# Cardiovascular Image Validation Pipeline Configuration
# FDA-compliant validation parameters for cardiovascular imaging systems

# Data Management Configuration
data:
  input_formats:
    - "dicom"
    - "nifti" 
    - "numpy"
    - "json"
  
  preprocessing:
    normalize_intensity: true
    clip_range: [-200, 800]  # HU range for cardiovascular CT
    target_spacing: [0.5, 0.5, 0.5]  # mm
    
  validation_split:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    stratify_by: "institution"  # Ensure balanced multi-center validation

# Vessel Segmentation Validation Parameters
vessel_validation:
  # Geometric accuracy thresholds
  dice_threshold: 0.7          # Minimum Dice coefficient for acceptance
  jaccard_threshold: 0.5       # Minimum Jaccard index
  hausdorff_threshold: 5.0     # Maximum Hausdorff distance (mm)
  
  # Topological validation
  connectivity_threshold: 0.95  # Minimum connectivity preservation
  centerline_accuracy_threshold: 0.8
  
  # Clinical metrics
  diameter_error_threshold: 0.15    # 15% maximum diameter measurement error
  length_error_threshold: 0.10      # 10% maximum length measurement error
  volume_error_threshold: 0.20      # 20% maximum volume measurement error
  
  # Quality assessment
  quality_weights:
    geometric_accuracy: 0.4
    topological_accuracy: 0.3
    clinical_relevance: 0.3

# Statistical Validation Parameters
statistical_validation:
  # Significance levels
  alpha: 0.05                  # Type I error rate
  beta: 0.20                   # Type II error rate (80% power)
  
  # Agreement thresholds
  icc_threshold: 0.75          # Minimum ICC for good agreement
  agreement_threshold: 0.8     # General agreement threshold
  power_threshold: 0.8         # Minimum statistical power
  
  # Bias assessment
  bias_threshold: 0.1          # Maximum acceptable bias (normalized)
  
  # Confidence intervals
  confidence_level: 0.95       # 95% confidence intervals
  bootstrap_samples: 1000      # Bootstrap iterations
  
  # Bland-Altman analysis
  bland_altman:
    calculate_proportional_bias: true
    confidence_intervals: true
    
  # Hypothesis testing
  normality_test: "shapiro"    # Test for normality assumption
  multiple_comparison_correction: "bonferroni"

# Bias Assessment Configuration
bias_assessment:
  # Fairness thresholds
  fairness_threshold: 0.8      # 80% demographic parity minimum
  statistical_alpha: 0.05     # Significance level for bias tests
  
  # Minimum group sizes
  min_group_size: 30           # Minimum samples per demographic group
  min_total_samples: 100       # Minimum total samples for bias analysis
  
  # Protected attributes to analyze
  protected_attributes:
    - "age_group"              # Young, middle-aged, elderly
    - "sex"                    # Male, female
    - "race"                   # Racial/ethnic groups
    - "ethnicity"              # Hispanic/Latino status
    - "institution"            # Hospital/clinic site
    - "insurance_type"         # Insurance status (if available)
    - "comorbidities"          # Presence of comorbidities
  
  # Fairness metrics
  fairness_metrics:
    - "demographic_parity"     # Equal positive rates
    - "equalized_odds"         # Equal TPR and FPR
    - "calibration_parity"     # Equal calibration across groups
    - "treatment_equality"     # Equal error rates
  
  # Intersectional analysis
  intersectional_analysis:
    enabled: true
    max_intersection_depth: 2  # Analyze up to 2-way intersections
    min_intersection_size: 20  # Minimum size for intersection groups

# Uncertainty Quantification Parameters
uncertainty:
  # Calibration thresholds
  calibration_threshold: 0.1   # Maximum Expected Calibration Error
  reliability_diagram_bins: 10 # Number of bins for reliability diagram
  
  # Confidence estimation
  confidence_level: 0.95       # 95% confidence intervals
  bootstrap_samples: 1000      # Bootstrap iterations
  uncertainty_threshold: 0.2   # Maximum acceptable uncertainty
  
  # Predictive uncertainty
  entropy_threshold: 0.5       # Maximum entropy for well-calibrated predictions
  
  # Calibration correction
  calibration_methods:
    - "platt_scaling"          # Logistic regression calibration
    - "isotonic_regression"    # Isotonic regression calibration
    - "temperature_scaling"    # Temperature scaling (if applicable)
  
  # Selective prediction
  selective_prediction:
    enabled: true
    coverage_levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    
  # Ensemble uncertainty (if applicable)
  ensemble_analysis:
    enabled: true
    min_ensemble_size: 3
    diversity_threshold: 0.1

# Reporting Configuration
reporting:
  # Report metadata
  report_title: "Cardiovascular Image Validation Report"
  organization: "Medical Imaging Validation Laboratory"
  template_style: "professional"
  
  # Output formats
  output_formats:
    - "html"                   # Interactive HTML report
    - "pdf"                    # PDF summary report
    - "json"                   # Machine-readable results
    - "csv"                    # Tabular data export
  
  # Visualization settings
  visualization:
    dpi: 300                   # High resolution for publication
    figure_format: "png"       # Figure format
    color_scheme: "professional" # Color scheme for plots
    include_interactive_plots: true
    
  # Regulatory documentation
  regulatory_package:
    generate_510k_summary: true
    generate_validation_protocol: true
    generate_statistical_plan: true
    generate_risk_analysis: true
    include_source_code: false  # For IP protection
    
  # FDA compliance features
  fda_compliance:
    include_predicate_comparison: true
    include_clinical_evaluation: true
    include_labeling_considerations: true
    include_post_market_surveillance: true

# Phantom Validation Configuration
phantom_validation:
  # Phantom types
  phantom_types:
    - "coronary_vessel"        # Coronary artery phantom
    - "cardiac_chamber"        # Cardiac chamber phantom
    - "flow_phantom"           # Flow measurement phantom
  
  # Geometric accuracy
  geometric_tolerance: 0.1     # mm tolerance for geometric measurements
  
  # Noise robustness
  noise_levels: [0.0, 0.05, 0.1, 0.15, 0.2]  # SNR degradation levels
  
  # Image quality parameters
  image_quality:
    resolution_levels: [1.0, 0.8, 0.6, 0.4]  # Relative resolution
    contrast_levels: [1.0, 0.8, 0.6, 0.4]    # Relative contrast

# Multi-center Validation
multi_center:
  # Site stratification
  min_sites: 3                 # Minimum number of sites
  min_samples_per_site: 50     # Minimum samples per site
  
  # Cross-site validation
  cross_validation:
    enabled: true
    folds: 5                   # 5-fold cross-validation
    stratify_by_site: true
    
  # Site effect analysis
  site_effect_analysis:
    enabled: true
    random_effects_model: true
    
# Clinical Validation Parameters
clinical_validation:
  # Primary endpoints
  primary_endpoints:
    - "diagnostic_accuracy"    # Sensitivity/specificity
    - "measurement_accuracy"   # Quantitative measurement accuracy
    - "clinical_workflow"      # Impact on clinical workflow
  
  # Secondary endpoints
  secondary_endpoints:
    - "inter_observer_agreement"
    - "intra_observer_agreement"
    - "time_to_diagnosis"
    - "confidence_assessment"
  
  # Clinical thresholds
  clinical_thresholds:
    sensitivity_threshold: 0.85      # Minimum sensitivity
    specificity_threshold: 0.90      # Minimum specificity
    ppv_threshold: 0.80             # Minimum positive predictive value
    npv_threshold: 0.95             # Minimum negative predictive value
    
  # Reader study parameters
  reader_study:
    min_readers: 3             # Minimum number of readers
    blinding: true             # Blinded assessment
    randomization: true        # Randomized case presentation
    training_cases: 10         # Training cases per reader

# Performance Monitoring
performance_monitoring:
  # Monitoring metrics
  key_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "calibration_error"
    - "bias_metrics"
  
  # Alert thresholds
  alert_thresholds:
    accuracy_drop: 0.05        # 5% accuracy drop triggers alert
    bias_increase: 0.1         # 10% bias increase triggers alert
    calibration_drift: 0.05    # 5% calibration drift triggers alert
  
  # Monitoring frequency
  monitoring_frequency: "monthly"  # Monthly performance review
  
  # Revalidation triggers
  revalidation_triggers:
    - "significant_performance_drop"
    - "new_demographic_groups"
    - "algorithm_updates"
    - "regulatory_requirements"

# Logging Configuration
logging:
  level: "INFO"                # Logging level
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log files
  log_files:
    validation_log: "logs/validation.log"
    error_log: "logs/errors.log"
    audit_log: "logs/audit.log"
  
  # Log rotation
  max_log_size: "10MB"
  backup_count: 5
  
# Security and Privacy
security:
  # Data anonymization
  anonymization:
    enabled: true
    method: "hash_based"       # Hash-based anonymization
    include_demographics: false # Don't log raw demographics
    
  # Audit trail
  audit_trail:
    enabled: true
    log_all_operations: true
    include_user_id: true
    
  # Data retention
  data_retention:
    validation_results: "7_years"  # FDA requirement
    raw_data: "2_years"
    logs: "3_years"
    